[package]
name = "ave"
version = "0.1.1-alpha"
authors = ["James Hiew <james@hiew.net>"]
edition = "2018"

[dependencies]
# OpenGL + UI
glium = "= 0.25.1"
glium_text = { git = "https://github.com/I3ck/glium_text", branch = "glium-0-25-0"}

# math
cgmath = "*"
collision = "*"
float-cmp = "*"
rand = "*"
noise = "*"

# logging
log = "*"
simplelog = "*"