[package]
name = "ave"
version = "0.1.1-alpha"
authors = ["James Hiew <james@hiew.net>"]
edition = "2018"

[dependencies]
# OpenGL + UI
glium = "= 0.25.1"
glium_text = "*"
glutin = "= 0.21.0"

# math
cgmath = "*"
collision = "*"
float-cmp = "*"
rand = "*"
noise = "*"

# logging
log = "*"
simplelog = "*"