[package]
name = "ave"
version = "0.2.0-alpha"
authors = ["James Hiew <james@hiew.net>"]
edition = "2018"
description = "Voxel based world generation in Rust"
readme = "README.md"
homepage = "https://github.com/jameshiew/ave"
repository = "https://github.com/jameshiew/ave"
license-file = "LICENSE.txt"
keywords = ["voxel", "glsl"]

[badges]
gitlab = { repository = "https://gitlab.com/jameshiew/ave" }

[dependencies]
# OpenGL + UI
glium = "*"

# math
cgmath = "*"
collision = "*"
float-cmp = "*"
rand = "*"
noise = "*"

# logging
log = "*"
simplelog = "*"