[package]
name = "ave"
version = "0.2.0-alpha"
authors = ["James Hiew <james@hiew.net>"]
edition = "2018"
description = "Voxel based world generation in Rust"
readme = "README.md"
homepage = "https://github.com/jameshiew/ave"
repository = "https://github.com/jameshiew/ave"
license-file = "LICENSE.txt"
keywords = ["voxel", "glsl"]

[badges]
gitlab = { repository = "https://gitlab.com/jameshiew/ave" }

[dependencies]
# OpenGL + UI
glium = "0.27"
glium_text = { git = "https://github.com/jameshiew/glium_text"}

# math
cgmath = "0.17"
collision = "0.20"
float-cmp = "0.6"
rand = "0.7"
noise = "0.6"

# instrumentation
prometheus = "0.8"

# logging
log = "0.4"
simplelog = "0.7"